/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import jFramesSecundarios.CadastrarProdutos;
import jFramesSecundarios.*;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Wolveraa
 */
public class PrincipalJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public PrincipalJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jPrincipal = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenuItem();
        jClientes = new javax.swing.JMenu();
        jMenuClientes = new javax.swing.JMenuItem();
        jMenuProdutos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/9537.jpg"))); // NOI18N

        jPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Info_10584.png"))); // NOI18N
        jPrincipal.setMnemonic('P');
        jPrincipal.setText("Inicio");

        jMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Exit_10583.png"))); // NOI18N
        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair(evt);
            }
        });
        jPrincipal.add(jMenuSair);

        jMenuBar1.add(jPrincipal);

        jClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_accessories-text-editor_118805.png"))); // NOI18N
        jClientes.setMnemonic('C');
        jClientes.setText("Cadastros");

        jMenuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_contact-new_23203.png"))); // NOI18N
        jMenuClientes.setText("Clientes");
        jMenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarClientes(evt);
            }
        });
        jClientes.add(jMenuClientes);

        jMenuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_basket_download_66688.png"))); // NOI18N
        jMenuProdutos.setText("Produtos");
        jMenuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProdutosListarProdutos(evt);
            }
        });
        jClientes.add(jMenuProdutos);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Profile_10593.png"))); // NOI18N
        jMenuItem1.setText("Funcionarios");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jClientes.add(jMenuItem1);

        jMenuBar1.add(jClientes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
////////////////METODO SAAAIR
    private void sair(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair
      System.exit(0);
    }//GEN-LAST:event_sair
///////////ABRE A TELA DE LISTAGEM
    private void ListarClientes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarClientes
         new ExibirClientes().show();
    }//GEN-LAST:event_ListarClientes

    private void jMenuProdutosListarProdutos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProdutosListarProdutos
          new ExibirProdutos().show();
    }//GEN-LAST:event_jMenuProdutosListarProdutos

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    new ExibirFuncionario().show();



    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
          /////// Função de deixar full screen
                PrincipalJFrame P = new PrincipalJFrame();
                P.setVisible(true);

                Toolkit tool = Toolkit.getDefaultToolkit();
                Dimension tamanho = tool.getScreenSize();

                P.setSize(tamanho);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuClientes;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuProdutos;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JMenu jPrincipal;
    // End of variables declaration//GEN-END:variables
}
