/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import jFramesSecundarios.ExibirClientes;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Wolveraa
 */
public class PrincipalJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public PrincipalJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jPrincipal = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenuItem();
        jClientes = new javax.swing.JMenu();
        jMenuClientes = new javax.swing.JMenuItem();
        jUtilitarios = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");

        jPrincipal.setMnemonic('P');
        jPrincipal.setText("Inicio");

        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair(evt);
            }
        });
        jPrincipal.add(jMenuSair);

        jMenuBar1.add(jPrincipal);

        jClientes.setMnemonic('C');
        jClientes.setText("Cadastros");

        jMenuClientes.setText("Clientes");
        jMenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarClientes(evt);
            }
        });
        jClientes.add(jMenuClientes);

        jMenuBar1.add(jClientes);

        jUtilitarios.setMnemonic('U');
        jUtilitarios.setText("Utilitarios");
        jMenuBar1.add(jUtilitarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
////////////////METODO SAAAIR
    private void sair(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair
      System.exit(0);
    }//GEN-LAST:event_sair
///////////ABRE A TELA DE LISTAGEM
    private void ListarClientes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarClientes
         new ExibirClientes().show();
    }//GEN-LAST:event_ListarClientes

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
          /////// Função de deixar full screen
                PrincipalJFrame P = new PrincipalJFrame();
                P.setVisible(true);

                Toolkit tool = Toolkit.getDefaultToolkit();
                Dimension tamanho = tool.getScreenSize();

                P.setSize(tamanho);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jClientes;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuClientes;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JMenu jPrincipal;
    private javax.swing.JMenu jUtilitarios;
    // End of variables declaration//GEN-END:variables
}
